// frontend-ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { NgIf, NgFor } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule, NgIf, NgFor],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  query = '0.1,0.2,0.3,0.4';
  loading = false;
  error = '';
  results: Array<{ id: number; score: number }> = [];

  constructor(private http: HttpClient) {}

  search() {
    this.loading = true;
    this.error = '';
    this.results = [];
    const vector = this.query.split(',').map(v => Number(v.trim())).filter(v => !Number.isNaN(v));
    this.http.post<Array<{ id: number; score: number }>>('/search', { vector })
      .subscribe({
        next: data => { this.results = data; this.loading = false; },
        error: err => { this.error = String(err?.message || err); this.loading = false; }
      });
  }
}

<h1>E-commerce Vector Search</h1>

<input [(ngModel)]="query" style="width:320px" placeholder="comma-separated vector" />
<button (click)="search()" [disabled]="loading">Search</button>

<p *ngIf="loading">Searching…</p>
<p *ngIf="!loading && error" style="color:red">Error: {{ error }}</p>

<ul *ngIf="!loading && !error && results.length">
  <li *ngFor="let r of results">id={{ r.id }} score={{ r.score | number:'1.3-3' }}</li>
</ul>

// frontend/src/App.svelte
<script lang="ts">
    import { onMount } from "svelte";
    let query = "0.1, 0.2, 0.3, 0.4";
    let result: any = null;
    let loading = false;
    let error = "";

    async function doSearch() {
        loading = true;
        error = "";
        result = null;
        try {
            const response = await fetch("http://localhost:8080/search", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ vector: query.split(",").map(Number) }),
            });
            if (!response.ok) throw new Error(await response.text());
            result = await response.json();
        } catch (err) {
            error = String(err);
        } finally {
            loading = false;
        }
    }
</script>

<h1>Vector Search Demo</h1>
<input bind:value={query} placeholder="Enter comma-separated vector" style="width: 300px;">
<button on:click={doSearch} disabled={loading}>Search</button>

{#if loading}
    <p>Searching…</p>
{:else if error}
    <p style="color: red">{error}</p>
{:else if result}
    <h2>Results</h2>
    <pre>{JSON.stringify(result, null, 2)}</pre>
{/if}
